
version: '3'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - JWT_SECRET=super-strong-secret-string
    restart: on-failure

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
